Repository exasim-project/FoamAdapter, pull requests merged in 2025-03, with the labels that each got.

#55 Improve the documentation of FoamAdapter on the main page
  README.md
Labels: documentation

#58 Make the tutorial case run successfully
  tutorials/scalarAdvection/system/controlDict
  tutorials/scalarAdvection/system/fvSolution
  tutorials/scalarAdvection/system/simulationParameters
Labels: ready-to-merge

#54 fix redundant label definitions
  .github/workflows/build.yaml
  .github/workflows/static_checks.yaml
  cmake/OpenFOAM.cmake
Labels: ready-for-review
